services:
  ai-app:
    container_name: ai-app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/ai-app
    restart: always
    env_file:
      - ./app/.env
    networks:
      - app-network

  next-app:
    container_name: next-app
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/next-app
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - 8080:3000
    depends_on:
      - ai-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
